language: python
python:
  - "3.6"
  - "3.6-dev"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install flake8"
script:
  - "flake8 fantasy"
#  - "python setup.py test"
#  - "pytest --cov=./"
after_success:
  - "codecov"
